import { MapMode } from "./MapMode";


export class Creature {
  id: number;
  name: string;
  lowestMapMode: MapMode;
  private constructor (id: number, name: string, lowestMapMode: MapMode) {
    this.id = id;
    this.name = name;
    this.lowestMapMode = lowestMapMode;
  }


  private static allCreatures = [
    new Creature(0,"Pikeman", MapMode.RestorationOfErathia),
new Creature(1,"Halberdier", MapMode.RestorationOfErathia),
new Creature(2,"Archer", MapMode.RestorationOfErathia),
new Creature(3,"Marksman", MapMode.RestorationOfErathia),
new Creature(4,"Griffin", MapMode.RestorationOfErathia),
new Creature(5,"Royal griffin", MapMode.RestorationOfErathia),
new Creature(6,"Swordsman", MapMode.RestorationOfErathia),
new Creature(7,"Crusader", MapMode.RestorationOfErathia),
new Creature(8,"Monk", MapMode.RestorationOfErathia),
new Creature(9,"Zealot", MapMode.RestorationOfErathia),
new Creature(10,"Cavalier", MapMode.RestorationOfErathia),
new Creature(11,"Champion", MapMode.RestorationOfErathia),
new Creature(12,"Angel", MapMode.RestorationOfErathia),
new Creature(13,"Archangel", MapMode.RestorationOfErathia),
new Creature(14,"Centaur", MapMode.RestorationOfErathia),
new Creature(15,"Centaur capitan", MapMode.RestorationOfErathia),
new Creature(16,"Dwarf", MapMode.RestorationOfErathia),
new Creature(17,"Battle dwarf", MapMode.RestorationOfErathia),
new Creature(18,"Wood elf", MapMode.RestorationOfErathia),
new Creature(19,"Grand elf", MapMode.RestorationOfErathia),
new Creature(20,"Pegasus", MapMode.RestorationOfErathia),
new Creature(21,"Silver pegasus", MapMode.RestorationOfErathia),
new Creature(22,"Dendroid guard", MapMode.RestorationOfErathia),
new Creature(23,"Dendroid solider", MapMode.RestorationOfErathia),
new Creature(24,"Unicorn", MapMode.RestorationOfErathia),
new Creature(25,"War unicorn", MapMode.RestorationOfErathia),
new Creature(26,"Green dragon", MapMode.RestorationOfErathia),
new Creature(27,"Gold dragon", MapMode.RestorationOfErathia),
new Creature(28,"Gremlin", MapMode.RestorationOfErathia),
new Creature(29,"Master gremlin", MapMode.RestorationOfErathia),
new Creature(30,"Stone gargoyle", MapMode.RestorationOfErathia),
new Creature(31,"Obsidian gargoyle", MapMode.RestorationOfErathia),
new Creature(32,"Stone golem", MapMode.RestorationOfErathia),
new Creature(33,"Iron golem", MapMode.RestorationOfErathia),
new Creature(34,"Mage", MapMode.RestorationOfErathia),
new Creature(35,"Arch mage", MapMode.RestorationOfErathia),
new Creature(36,"Genie", MapMode.RestorationOfErathia),
new Creature(37,"Master genie", MapMode.RestorationOfErathia),
new Creature(38,"Naga", MapMode.RestorationOfErathia),
new Creature(39,"Naga queen", MapMode.RestorationOfErathia),
new Creature(40,"Giant", MapMode.RestorationOfErathia),
new Creature(41,"Titan", MapMode.RestorationOfErathia),
new Creature(42,"Imp", MapMode.RestorationOfErathia),
new Creature(43,"Familiar", MapMode.RestorationOfErathia),
new Creature(44,"Gog", MapMode.RestorationOfErathia),
new Creature(45,"Magog", MapMode.RestorationOfErathia),
new Creature(46,"Hell hound", MapMode.RestorationOfErathia),
new Creature(47,"Cerberus", MapMode.RestorationOfErathia),
new Creature(48,"Daemon", MapMode.RestorationOfErathia),
new Creature(49,"Horned daemon", MapMode.RestorationOfErathia),
new Creature(50,"Pit fiend", MapMode.RestorationOfErathia),
new Creature(51,"Pit lord", MapMode.RestorationOfErathia),
new Creature(52,"Efreet", MapMode.RestorationOfErathia),
new Creature(53,"Efreet sultan", MapMode.RestorationOfErathia),
new Creature(54,"Devil", MapMode.RestorationOfErathia),
new Creature(55,"Arch Devil", MapMode.RestorationOfErathia),
new Creature(56,"Skeleton", MapMode.RestorationOfErathia),
new Creature(57,"Skeleton Warrior", MapMode.RestorationOfErathia),
new Creature(58,"Walking dead", MapMode.RestorationOfErathia),
new Creature(59,"Zombie", MapMode.RestorationOfErathia),
new Creature(60,"Wight", MapMode.RestorationOfErathia),
new Creature(61,"Wraight", MapMode.RestorationOfErathia),
new Creature(62,"Vampire", MapMode.RestorationOfErathia),
new Creature(63,"Vampire lord", MapMode.RestorationOfErathia),
new Creature(64,"Lich", MapMode.RestorationOfErathia),
new Creature(65,"Power Lich", MapMode.RestorationOfErathia),
new Creature(66,"Black knight", MapMode.RestorationOfErathia),
new Creature(67,"Dead knight", MapMode.RestorationOfErathia),
new Creature(68,"Bone dragon", MapMode.RestorationOfErathia),
new Creature(69,"Ghost dragon", MapMode.RestorationOfErathia),
new Creature(70,"Tryglodyte", MapMode.RestorationOfErathia),
new Creature(71,"Infernal tryglodyte", MapMode.RestorationOfErathia),
new Creature(72,"Harpy", MapMode.RestorationOfErathia),
new Creature(73,"Harpy hag", MapMode.RestorationOfErathia),
new Creature(74,"Beholder", MapMode.RestorationOfErathia),
new Creature(75,"Evil eve", MapMode.RestorationOfErathia),
new Creature(76,"Medusa", MapMode.RestorationOfErathia),
new Creature(77,"Medusa queen", MapMode.RestorationOfErathia),
new Creature(78,"Minotaur", MapMode.RestorationOfErathia),
new Creature(79,"Minotaur king", MapMode.RestorationOfErathia),
new Creature(80,"Manticore", MapMode.RestorationOfErathia),
new Creature(81,"Scorpicore", MapMode.RestorationOfErathia),
new Creature(82,"Red dragon", MapMode.RestorationOfErathia),
new Creature(83,"Black dragon", MapMode.RestorationOfErathia),
new Creature(84,"Goblin", MapMode.RestorationOfErathia),
new Creature(85,"Hobgoblin", MapMode.RestorationOfErathia),
new Creature(86,"Wolf rider", MapMode.RestorationOfErathia),
new Creature(87,"Wolf raider", MapMode.RestorationOfErathia),
new Creature(88,"Orc", MapMode.RestorationOfErathia),
new Creature(89,"Orc chieftain", MapMode.RestorationOfErathia),
new Creature(90,"Ogre", MapMode.RestorationOfErathia),
new Creature(91,"Ogre mage", MapMode.RestorationOfErathia),
new Creature(92,"Roc", MapMode.RestorationOfErathia),
new Creature(93,"Thunderbird", MapMode.RestorationOfErathia),
new Creature(94,"Cyclops", MapMode.RestorationOfErathia),
new Creature(95,"Cyclops king", MapMode.RestorationOfErathia),
new Creature(96,"Behemoth", MapMode.RestorationOfErathia),
new Creature(97,"Ancient behemoth", MapMode.RestorationOfErathia),
new Creature(98,"Gnoll", MapMode.RestorationOfErathia),
new Creature(99,"Gnoll marauder", MapMode.RestorationOfErathia),
new Creature(100,"Lizardman", MapMode.RestorationOfErathia),
new Creature(101,"Lizard warrior", MapMode.RestorationOfErathia),
new Creature(102,"Serpent fly", MapMode.RestorationOfErathia),
new Creature(103,"Dragonfly", MapMode.RestorationOfErathia),
new Creature(104,"Basilisk", MapMode.RestorationOfErathia),
new Creature(105,"Greater Basilisk", MapMode.RestorationOfErathia),
new Creature(106,"Gorgon", MapMode.RestorationOfErathia),
new Creature(107,"Mighty gorgon", MapMode.RestorationOfErathia),
new Creature(108,"Wyvern", MapMode.RestorationOfErathia),
new Creature(109,"Wyvern Monarch", MapMode.RestorationOfErathia),
new Creature(110,"Hydra", MapMode.RestorationOfErathia),
new Creature(111,"Chaos hydra", MapMode.RestorationOfErathia),
new Creature(112,"Air elemental", MapMode.RestorationOfErathia),
new Creature(113,"Earth elemental", MapMode.RestorationOfErathia),
new Creature(114,"Fire elemental", MapMode.RestorationOfErathia),
new Creature(115,"Water elemental", MapMode.RestorationOfErathia),
new Creature(116,"Golem", MapMode.RestorationOfErathia),
new Creature(117,"Diamond golem", MapMode.RestorationOfErathia),
new Creature(118,"Pixies", MapMode.ArmageddonSBlade),
new Creature(119,"Sprites", MapMode.ArmageddonSBlade),
new Creature(120,"Phychic elemental", MapMode.ArmageddonSBlade),
new Creature(121,"Magic elemental", MapMode.ArmageddonSBlade),
new Creature(122,"Ice elemental", MapMode.ArmageddonSBlade),
new Creature(123,"Magma elemental", MapMode.ArmageddonSBlade),
new Creature(124,"Storm elemental", MapMode.ArmageddonSBlade),
new Creature(125,"Energy elemental", MapMode.ArmageddonSBlade),
new Creature(126,"Firebird", MapMode.ArmageddonSBlade),
new Creature(127,"Phoenix", MapMode.ArmageddonSBlade),
new Creature(128,"Azure dragons", MapMode.ArmageddonSBlade),
new Creature(129,"Crystal dragons", MapMode.ArmageddonSBlade),
new Creature(130,"Faeri dragons", MapMode.ArmageddonSBlade),
new Creature(131,"Rust dragons", MapMode.ArmageddonSBlade),
new Creature(132,"Enchanters", MapMode.ArmageddonSBlade),
new Creature(133,"Sharpshooters", MapMode.ArmageddonSBlade),
new Creature(134,"Halflings", MapMode.ArmageddonSBlade),
new Creature(135,"Peasants", MapMode.ArmageddonSBlade),
new Creature(136,"Boars", MapMode.ArmageddonSBlade),
new Creature(137,"Mummies", MapMode.ArmageddonSBlade),
new Creature(138,"Nomads", MapMode.ArmageddonSBlade),
new Creature(139,"Rogues", MapMode.ArmageddonSBlade),
new Creature(140,"Trolls", MapMode.ArmageddonSBlade),
  ];

  public static getAll(mode: MapMode): Creature[] {
    return Creature.allCreatures.filter(c =>  mode >= c.lowestMapMode);
  }
}
