import { MapMode } from "./MapMode";

export class HeroDefinition {
  name: string;
  heroClass: string;
  minMode: MapMode;

  private constructor(name: string, heroClass: string, minMode: MapMode) {
    this.name = name;
    this.heroClass = heroClass;
    this.minMode = minMode;
  }

  private static allHeroes = [
    new HeroDefinition("Christian", "Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Edric", "Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Orrin", "Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Sylvia", "Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Valeska", "Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Sorsha", "Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Tyris", "Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Lord Haart", "Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Catherine", "Knight", MapMode.ArmageddonSBlade),
new HeroDefinition("Roland", "Knight", MapMode.ArmageddonSBlade),
new HeroDefinition("Sir Mullich", "Knight", MapMode.ArmageddonSBlade),
new HeroDefinition("Adela", "Cleric", MapMode.RestorationOfErathia),
new HeroDefinition("Adelaide", "Cleric", MapMode.RestorationOfErathia),
new HeroDefinition("Caitlin", "Cleric", MapMode.RestorationOfErathia),
new HeroDefinition("Cuthbert", "Cleric", MapMode.RestorationOfErathia),
new HeroDefinition("Ingham", "Cleric", MapMode.RestorationOfErathia),
new HeroDefinition("Loynis", "Cleric", MapMode.RestorationOfErathia),
new HeroDefinition("Rion", "Cleric", MapMode.RestorationOfErathia),
new HeroDefinition("Sanya", "Cleric", MapMode.RestorationOfErathia),
new HeroDefinition("Jenova", "Ranger", MapMode.RestorationOfErathia),
new HeroDefinition("Kyrre", "Ranger", MapMode.RestorationOfErathia),
new HeroDefinition("Ivor", "Ranger", MapMode.RestorationOfErathia),
new HeroDefinition("Ufretin", "Ranger", MapMode.RestorationOfErathia),
new HeroDefinition("Clancy", "Ranger", MapMode.RestorationOfErathia),
new HeroDefinition("Thorgrim", "Ranger", MapMode.RestorationOfErathia),
new HeroDefinition("Ryland", "Ranger", MapMode.RestorationOfErathia),
new HeroDefinition("Mephala", "Ranger", MapMode.RestorationOfErathia),
new HeroDefinition("Gelu", "Ranger", MapMode.ArmageddonSBlade),
new HeroDefinition("Aeris", "Druid", MapMode.RestorationOfErathia),
new HeroDefinition("Alagar", "Druid", MapMode.RestorationOfErathia),
new HeroDefinition("Coronius", "Druid", MapMode.RestorationOfErathia),
new HeroDefinition("Elleshar", "Druid", MapMode.RestorationOfErathia),
new HeroDefinition("Malcom", "Druid", MapMode.RestorationOfErathia),
new HeroDefinition("Melodia", "Druid", MapMode.RestorationOfErathia),
new HeroDefinition("Gem", "Druid", MapMode.RestorationOfErathia),
new HeroDefinition("Uland", "Druid", MapMode.RestorationOfErathia),
new HeroDefinition("Fafner", "Alchemist", MapMode.RestorationOfErathia),
new HeroDefinition("Iona", "Alchemist", MapMode.RestorationOfErathia),
new HeroDefinition("Josephine", "Alchemist", MapMode.RestorationOfErathia),
new HeroDefinition("Neela", "Alchemist", MapMode.RestorationOfErathia),
new HeroDefinition("Piquedram", "Alchemist", MapMode.RestorationOfErathia),
new HeroDefinition("Rissa", "Alchemist", MapMode.RestorationOfErathia),
new HeroDefinition("Thane", "Alchemist", MapMode.RestorationOfErathia),
new HeroDefinition("Torosar", "Alchemist", MapMode.RestorationOfErathia),
new HeroDefinition("Aine", "Wizard", MapMode.RestorationOfErathia),
new HeroDefinition("Astral", "Wizard", MapMode.RestorationOfErathia),
new HeroDefinition("Cyra", "Wizard", MapMode.RestorationOfErathia),
new HeroDefinition("Daremyth", "Wizard", MapMode.RestorationOfErathia),
new HeroDefinition("Halon", "Wizard", MapMode.RestorationOfErathia),
new HeroDefinition("Serena", "Wizard", MapMode.RestorationOfErathia),
new HeroDefinition("Solmyr", "Wizard", MapMode.RestorationOfErathia),
new HeroDefinition("Theodorus", "Wizard", MapMode.RestorationOfErathia),
new HeroDefinition("Dracon", "Wizard", MapMode.ArmageddonSBlade),
new HeroDefinition("Calh", "Demoniac", MapMode.RestorationOfErathia),
new HeroDefinition("Fiona", "Demoniac", MapMode.RestorationOfErathia),
new HeroDefinition("Ignatius", "Demoniac", MapMode.RestorationOfErathia),
new HeroDefinition("Marius", "Demoniac", MapMode.RestorationOfErathia),
new HeroDefinition("Nymus", "Demoniac", MapMode.RestorationOfErathia),
new HeroDefinition("Octavia", "Demoniac", MapMode.RestorationOfErathia),
new HeroDefinition("Pyre", "Demoniac", MapMode.RestorationOfErathia),
new HeroDefinition("Rashka", "Demoniac", MapMode.RestorationOfErathia),
new HeroDefinition("Xeron", "Demoniac", MapMode.ArmageddonSBlade),
new HeroDefinition("Ash", "Heretic", MapMode.RestorationOfErathia),
new HeroDefinition("Axsis", "Heretic", MapMode.RestorationOfErathia),
new HeroDefinition("Ayden", "Heretic", MapMode.RestorationOfErathia),
new HeroDefinition("Calid", "Heretic", MapMode.RestorationOfErathia),
new HeroDefinition("Olema", "Heretic", MapMode.RestorationOfErathia),
new HeroDefinition("Xyron", "Heretic", MapMode.RestorationOfErathia),
new HeroDefinition("Xarfax", "Heretic", MapMode.RestorationOfErathia),
new HeroDefinition("Zydar", "Heretic", MapMode.RestorationOfErathia),
new HeroDefinition("Charna", "Death Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Clavius", "Death Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Galthran", "Death Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Isra", "Death Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Moandor", "Death Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Straker", "Death Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Tamika", "Death Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Vokial", "Death Knight", MapMode.RestorationOfErathia),
new HeroDefinition("Lord Haart", "Death Knight", MapMode.ShadowOfDeath),
new HeroDefinition("Aislinn", "Necromancer", MapMode.RestorationOfErathia),
new HeroDefinition("Nagash", "Necromancer", MapMode.RestorationOfErathia),
new HeroDefinition("Nimbus", "Necromancer", MapMode.RestorationOfErathia),
new HeroDefinition("Sandro", "Necromancer", MapMode.RestorationOfErathia),
new HeroDefinition("Septienna", "Necromancer", MapMode.RestorationOfErathia),
new HeroDefinition("Thant", "Necromancer", MapMode.RestorationOfErathia),
new HeroDefinition("Vidomina", "Necromancer", MapMode.RestorationOfErathia),
new HeroDefinition("Xsi", "Necromancer", MapMode.RestorationOfErathia),
new HeroDefinition("Ajit", "Overlord", MapMode.RestorationOfErathia),
new HeroDefinition("Arlach", "Overlord", MapMode.RestorationOfErathia),
new HeroDefinition("Dace", "Overlord", MapMode.RestorationOfErathia),
new HeroDefinition("Damacon", "Overlord", MapMode.RestorationOfErathia),
new HeroDefinition("Gunnar", "Overlord", MapMode.RestorationOfErathia),
new HeroDefinition("Lorelei", "Overlord", MapMode.RestorationOfErathia),
new HeroDefinition("Shakti", "Overlord", MapMode.RestorationOfErathia),
new HeroDefinition("Synca", "Overlord", MapMode.RestorationOfErathia),
new HeroDefinition("Mutare", "Overlord", MapMode.ArmageddonSBlade),
new HeroDefinition("Mutare Drake", "Overlord", MapMode.ArmageddonSBlade),
new HeroDefinition("Alamar", "Warlock", MapMode.RestorationOfErathia),
new HeroDefinition("Darkstorn", "Warlock", MapMode.RestorationOfErathia),
new HeroDefinition("Deemer", "Warlock", MapMode.RestorationOfErathia),
new HeroDefinition("Geon", "Warlock", MapMode.RestorationOfErathia),
new HeroDefinition("Jaegar", "Warlock", MapMode.RestorationOfErathia),
new HeroDefinition("Jeddite", "Warlock", MapMode.RestorationOfErathia),
new HeroDefinition("Malekith", "Warlock", MapMode.RestorationOfErathia),
new HeroDefinition("Sephinroth", "Warlock", MapMode.RestorationOfErathia),
new HeroDefinition("Crag Hack", "Barbarian", MapMode.RestorationOfErathia),
new HeroDefinition("Gretchin", "Barbarian", MapMode.RestorationOfErathia),
new HeroDefinition("Gurnisson", "Barbarian", MapMode.RestorationOfErathia),
new HeroDefinition("Jabarkas", "Barbarian", MapMode.RestorationOfErathia),
new HeroDefinition("Krellion", "Barbarian", MapMode.RestorationOfErathia),
new HeroDefinition("Shiva", "Barbarian", MapMode.RestorationOfErathia),
new HeroDefinition("Tyraxor", "Barbarian", MapMode.RestorationOfErathia),
new HeroDefinition("Yog", "Barbarian", MapMode.RestorationOfErathia),
new HeroDefinition("Boragus", "Barbarian", MapMode.ArmageddonSBlade),
new HeroDefinition("Kilgor", "Barbarian", MapMode.ArmageddonSBlade),
new HeroDefinition("Dessa", "Battle Mage", MapMode.RestorationOfErathia),
new HeroDefinition("Gird", "Battle Mage", MapMode.RestorationOfErathia),
new HeroDefinition("Gundula", "Battle Mage", MapMode.RestorationOfErathia),
new HeroDefinition("Oris", "Battle Mage", MapMode.RestorationOfErathia),
new HeroDefinition("Saurug", "Battle Mage", MapMode.RestorationOfErathia),
new HeroDefinition("Terek", "Battle Mage", MapMode.RestorationOfErathia),
new HeroDefinition("Vey", "Battle Mage", MapMode.RestorationOfErathia),
new HeroDefinition("Zubin", "Battle Mage", MapMode.RestorationOfErathia),
new HeroDefinition("Alkin", "Beastmaster", MapMode.RestorationOfErathia),
new HeroDefinition("Broghild", "Beastmaster", MapMode.RestorationOfErathia),
new HeroDefinition("Bron", "Beastmaster", MapMode.RestorationOfErathia),
new HeroDefinition("Drakon", "Beastmaster", MapMode.RestorationOfErathia),
new HeroDefinition("Gerwulf", "Beastmaster", MapMode.RestorationOfErathia),
new HeroDefinition("Korbac", "Beastmaster", MapMode.RestorationOfErathia),
new HeroDefinition("Tazar", "Beastmaster", MapMode.RestorationOfErathia),
new HeroDefinition("Wystan", "Beastmaster", MapMode.RestorationOfErathia),
new HeroDefinition("Andra", "Witch", MapMode.RestorationOfErathia),
new HeroDefinition("Merist", "Witch", MapMode.RestorationOfErathia),
new HeroDefinition("Mirlanda", "Witch", MapMode.RestorationOfErathia),
new HeroDefinition("Rosic", "Witch", MapMode.RestorationOfErathia),
new HeroDefinition("Styg", "Witch", MapMode.RestorationOfErathia),
new HeroDefinition("Tiva", "Witch", MapMode.RestorationOfErathia),
new HeroDefinition("Verdish", "Witch", MapMode.RestorationOfErathia),
new HeroDefinition("Voy", "Witch", MapMode.RestorationOfErathia),
new HeroDefinition("Adrienne", "Witch", MapMode.ArmageddonSBlade),
new HeroDefinition("Erdamon", "Planeswalker", MapMode.RestorationOfErathia),
new HeroDefinition("Fiur", "Planeswalker", MapMode.RestorationOfErathia),
new HeroDefinition("Ignissa", "Planeswalker", MapMode.RestorationOfErathia),
new HeroDefinition("Kalt", "Planeswalker", MapMode.RestorationOfErathia),
new HeroDefinition("Lacus", "Planeswalker", MapMode.RestorationOfErathia),
new HeroDefinition("Monere", "Planeswalker", MapMode.RestorationOfErathia),
new HeroDefinition("Pasis", "Planeswalker", MapMode.RestorationOfErathia),
new HeroDefinition("Thunar", "Planeswalker", MapMode.RestorationOfErathia),
new HeroDefinition("Aenain", "Elementalist", MapMode.RestorationOfErathia),
new HeroDefinition("Brissa", "Elementalist", MapMode.RestorationOfErathia),
new HeroDefinition("Ciele", "Elementalist", MapMode.RestorationOfErathia),
new HeroDefinition("Gelare", "Elementalist", MapMode.RestorationOfErathia),
new HeroDefinition("Grindan", "Elementalist", MapMode.RestorationOfErathia),
new HeroDefinition("Inteus", "Elementalist", MapMode.RestorationOfErathia),
new HeroDefinition("Labetha", "Elementalist", MapMode.RestorationOfErathia),
new HeroDefinition("Luna", "Elementalist", MapMode.RestorationOfErathia),
  ];

  public static getAll(mapMode: MapMode) {
    return HeroDefinition.allHeroes.filter(h => mapMode >= h.minMode);
  }
}
